### PR TITLE
Cleaned up package json. Added documentjs.

### PR DESCRIPTION
**Pull request by Macrofig**
Was so focused on getting this done that I didn't realize I was in master.  

- DocumentJS is working.
- QUnit tests are working. I don't like that we have to manually tell QUnit to run when tests are ready but we can fix that later.
- The autocomplete is pretty prod ready but it will probably need another feature or two to be widely useful.
- Zero styling, it is expected that it will be styled by implementation. Every element has classes for styling ease, though.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Just use steal-quint and you shouldn't have to tell the tests when to run.

**Comment by Macrofig** [comment]
I removed it because it's using a slightly older version of QUnit.  I couldn't use `assert.async` for example. I would have been forced to use `asyncTest` which is deprecated.  I can switch back but can we update to newer qunit first?

**Comment by Macrofig** [comment]
Never mind, just saw Matthew's changes.

**Comment by matthewp** [comment]
@Macrofig is the new version of qunit still backwards compatible with the current (non-published) version we're using?

**Comment by Macrofig** [comment]
@matthewp I assumed non-published version was using most recent 1.x qunit, which is what I used here. So, yes? 

At worst, I am using `beforeEach` and `async`, both of which were added in 1.16.

**Comment by ccummings** [comment]
Closing this because these changes (and more) were done in #2

**Pull request closed without merging**
